displayName: LocusZoom DataSources

/linkage: !include ./locuszoom/linkage-api.raml
/gene: !include ./locuszoom/gene-api.raml
/recomb: !include ./locuszoom/recomb-api.raml
/gwas: !include ./locuszoom/gwas-api.raml
