displayName: Variant Record Lookups

/: !include ./variant/lookup.raml
/variant/gwas/hits: !include ./variant/hits.raml
#/linkage/block: !include ./variant/ldwindow.raml
#/linkage/expansion: !include ./variant/ld.raml
