linkage:
    type: object
    properties:
        id2:
            required: true
            type: array
            minItems: 1
        value:
            required: true
            type: array
            minItems: 1