displayName: LocusZoom DataSource API - Linkage Disequilibrium

types:
    linkage: !include ./locuszoom/types/linkage.raml


get: 
    description: > 
        return variants in LD (and correlations) with reference variant in format 
        expected by LocusZoom.js
    queryParameters:
        variant: primary key of the variant record serving as the reference
        start: start of display window
        end: end of display windwo
        population: unique ID for the population
        score: one of r2 or dprime
    responses:
        200:
            body:
                application/json:
                    type: types/linkage
