displayName: Variant LD Window


get: 
    description: > 
        return span of LD block enclosing the variant
    queryParameters:
        variant: variant identifier (rsId, chr:pos:ref:alt, or NIAGADS GenomicsDB primaryKey)
        population: unique ID for the population
        r2: r-squared threshold (optional) -- default 0.5
        maf: minor allele frequency threshold (option) -- default none
    responses:
        200:
            body:
                application/json:
                    example: {}
