displayName: Variant Lookup


get: 
    description: > 
        return basic information for a variant
    queryParameters:
        id: comma separated list of one or more variant identifiers (rsId, chr:pos:ref:alt, or NIAGADS GenomicsDB primaryKey)
    responses:
        200:
            body:
                application/json:
                    example: {}
