// WARNING: Do not edit this file directly. -- NOTE: temporary patch to handle GRCh37 & GRCh38 until script below is reworked
// Then run `python $PROJECT_HOME/GenomicsDBWebsite/Model/bin/generateSiteStatisticsJson` to regenerate this file.
// DB creds must be specified in $GUS_HOME/config/gus.config` to regenerate this file
export const _siteStatistics = {
    GRCh37: {
        ANNOTATED_VARIANTS: 41944992,
        DATASETS: 113,
        SIGNIFICANT_VARIANTS: 6649,
        ANNOTATED_GENES: 3489,
    },
    GRCh38: {
        ANNOTATED_VARIANTS: 263481007,
        DATASETS: 56,
        SIGNIFICANT_VARIANTS: 295901,
        ANNOTATED_GENES: 20656,
    },
};
