export interface Track {
    type: string;
    track: string;
    description: string;
    antibody_target: string;
    cell_line: string;
    cell: string;
    diagnosis: string;
    source: string;
    format: string;
    url: string;
}

const tracks: Track[] = [
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGEN000001",
        source: "ENCODE",
        cell_line: "A549",
        format: "bed broadPeak",
        url: "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/ChIP-seq/broadpeak/hg19/ENCFF000AIA.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGEN000009",
        source: "ENCODE",
        cell_line: "endothelial cell of umbilical vein",
        format: "bed broadPeak",
        url: "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/ChIP-seq/broadpeak/hg19/ENCFF000BSP.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGEN000387",
        source: "ENCODE",
        cell_line: "HepG2",
        format: "bed narrowPeak",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/ChIP-seq/narrowpeak/hg19/ENCFF000XVU.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGEN000388",
        source: "ENCODE",
        cell_line: "HepG2",
        format: "bed narrowPeak",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/ChIP-seq/narrowpeak/hg19/ENCFF000XWA.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGEN000389",
        source: "ENCODE",
        cell_line: "HepG2",
        format: "bed narrowPeak",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/ChIP-seq/narrowpeak/hg19/ENCFF000XWL.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGEN000429",
        source: "ENCODE",
        cell_line: "GM12878",
        format: "bed bed12",
        url: "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/5C/bed12/hg19/ENCFF000ZYR.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGEN000430",
        source: "ENCODE",
        cell_line: "H1-hESC",
        format: "bed bed12",
        url: "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/5C/bed12/hg19/ENCFF000ZZP.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGEN000431",
        source: "ENCODE",
        cell_line: "HeLa-S3",
        format: "bed bed12",
        url: "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/5C/bed12/hg19/ENCFF001AAR.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGEN000448",
        source: "ENCODE",
        cell_line: "MCF-7",
        format: "bed bed9",
        url: "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/CAGE/bed9/hg19/ENCFF002QES.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGEN000449",
        source: "ENCODE",
        cell_line: "GM06990",
        format: "bed narrowPeak",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/ChIP-seq/narrowpeak/hg19/ENCFF002TSG.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGEN000470",
        source: "ENCODE",
        cell_line: "Keratinocyte",
        format: "bed tss_peak",
        url: "https://tf.lisanwanglab.org/GADB/Annotationtracks/ENCODE/data/CAGE/tss_peak/hg19/ENCFF004EYA.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000001",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M0) cell line:Kasumi-3",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.LQhCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M0%2529%2520cell%2520line%253aKasumi-3.CNhs13241.10789-110H6.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000002",
        source: "FANTOM5",
        cell_line: "leiomyosarcoma cell line:Hs 5.T",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.LQhCAGE/bed6/hg19/leiomyosarcoma%2520cell%2520line%253aHs%25205%252eT.CNhs12192.10722-110A2.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000003",
        source: "FANTOM5",
        cell_line: "mesodermal tumor cell line:HIRS-BM",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.LQhCAGE/bed6/hg19/mesodermal%2520tumor%2520cell%2520line%253aHIRS-BM.CNhs12191.10696-109G3.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000004",
        source: "FANTOM5",
        cell_line: "mesothelioma cell line:Mero-14, tech_rep2",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.LQhCAGE/bed6/hg19/mesothelioma%2520cell%2520line%253aMero-14%252c%2520tech_rep2.CNhs14376.10849-111F3.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000005",
        source: "FANTOM5",
        cell_line: "non-small cell lung cancer cell line:NCI-H1385",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.LQhCAGE/bed6/hg19/non-small%2520cell%2520lung%2520cancer%2520cell%2520line%253aNCI-H1385.CNhs12193.10730-110B1.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000006",
        source: "FANTOM5",
        cell_line: "acantholytic squamous carcinoma cell line:HCC1806",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acantholytic%2520squamous%2520carcinoma%2520cell%2520line%253aHCC1806.CNhs11844.10717-109I6.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000007",
        source: "FANTOM5",
        cell_line: "acute lymphoblastic leukemia (B-ALL) cell line:BALL-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520lymphoblastic%2520leukemia%2520%2528B-ALL%2529%2520cell%2520line%253aBALL-1.CNhs11251.10455-106G5.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000008",
        source: "FANTOM5",
        cell_line: "acute lymphoblastic leukemia (B-ALL) cell line:NALM-6",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520lymphoblastic%2520leukemia%2520%2528B-ALL%2529%2520cell%2520line%253aNALM-6.CNhs11282.10534-107G3.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000009",
        source: "FANTOM5",
        cell_line: "acute lymphoblastic leukemia (T-ALL) cell line:HPB-ALL",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520lymphoblastic%2520leukemia%2520%2528T-ALL%2529%2520cell%2520line%253aHPB-ALL.CNhs10746.10429-106D6.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000010",
        source: "FANTOM5",
        cell_line: "acute lymphoblastic leukemia (T-ALL) cell line:Jurkat",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520lymphoblastic%2520leukemia%2520%2528T-ALL%2529%2520cell%2520line%253aJurkat.CNhs11253.10464-106H5.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000011",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M0) cell line:KG-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M0%2529%2520cell%2520line%253aKG-1.CNhs13053.10827-111C8.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000012",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M1) cell line:HYT-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M1%2529%2520cell%2520line%253aHYT-1.CNhs13054.10828-111C9.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000013",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M2) cell line:Kasumi-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M2%2529%2520cell%2520line%253aKasumi-1.CNhs13502.10788-110H5.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000014",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M2) cell line:Kasumi-6",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M2%2529%2520cell%2520line%253aKasumi-6.CNhs13052.10792-110H9.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000015",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M2) cell line:NKM-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M2%2529%2520cell%2520line%253aNKM-1.CNhs11864.10765-110E9.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000016",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M3) cell line:HL60",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M3%2529%2520cell%2520line%253aHL60.CNhs13055.10829-111D1.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000017",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M4) cell line:FKH-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M4%2529%2520cell%2520line%253aFKH-1.CNhs13503.10830-111D2.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000018",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M4) cell line:HNT-34",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M4%2529%2520cell%2520line%253aHNT-34.CNhs13504.10831-111D3.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000019",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M4eo) cell line:EoL-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M4eo%2529%2520cell%2520line%253aEoL-1.CNhs13056.10832-111D4.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000020",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M4eo) cell line:EoL-3",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M4eo%2529%2520cell%2520line%253aEoL-3.CNhs13057.10833-111D5.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000021",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M5) cell line:NOMO-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M5%2529%2520cell%2520line%253aNOMO-1.CNhs13050.10764-110E8.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000022",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M5) cell line:P31/FUJ",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M5%2529%2520cell%2520line%253aP31%252fFUJ.CNhs13051.10770-110F5.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000023",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M5) cell line:THP-1 (fresh)",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M5%2529%2520cell%2520line%253aTHP-1%2520%2528fresh%2529.CNhs10722.10399-106A3.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000024",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M5) cell line:THP-1 (revived)",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M5%2529%2520cell%2520line%253aTHP-1%2520%2528revived%2529.CNhs10723.10400-106A4.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000025",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M5) cell line:THP-1 (thawed)",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M5%2529%2520cell%2520line%253aTHP-1%2520%2528thawed%2529.CNhs10724.10405-106A9.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000026",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M5) cell line:U-937 DE-4",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M5%2529%2520cell%2520line%253aU-937%2520DE-4.CNhs13058.10834-111D6.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000027",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M6) cell line:EEB",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M6%2529%2520cell%2520line%253aEEB.CNhs13059.10835-111D7.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000028",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M6) cell line:F-36E",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M6%2529%2520cell%2520line%253aF-36E.CNhs13060.10836-111D8.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000029",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M6) cell line:F-36P",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M6%2529%2520cell%2520line%253aF-36P.CNhs13505.10837-111D9.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000030",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M7) cell line:MKPL-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M7%2529%2520cell%2520line%253aMKPL-1.CNhs11888.10802-111A1.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000031",
        source: "FANTOM5",
        cell_line: "acute myeloid leukemia (FAB M7) cell line:M-MOK",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/acute%2520myeloid%2520leukemia%2520%2528FAB%2520M7%2529%2520cell%2520line%253aM-MOK.CNhs13049.10699-109G6.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000032",
        source: "FANTOM5",
        cell_line: "adenocarcinoma cell line:IM95m",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/adenocarcinoma%2520cell%2520line%253aIM95m.CNhs11882.10796-110I4.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000033",
        source: "FANTOM5",
        cell_line: "adrenal cortex adenocarcinoma cell line:SW-13",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/adrenal%2520cortex%2520adenocarcinoma%2520cell%2520line%253aSW-13.CNhs11893.10810-111A9.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000034",
        source: "FANTOM5",
        cell_line: "adult T-cell leukemia cell line:ATN-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/adult%2520T-cell%2520leukemia%2520cell%2520line%253aATN-1.CNhs10738.10421-106C7.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000035",
        source: "FANTOM5",
        cell_line: "alveolar cell carcinoma cell line:SW 1573",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/alveolar%2520cell%2520carcinoma%2520cell%2520line%253aSW%25201573.CNhs11838.10708-109H6.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000036",
        source: "FANTOM5",
        cell_line: "anaplastic carcinoma cell line:8305C",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/anaplastic%2520carcinoma%2520cell%2520line%253a8305C.CNhs10745.10428-106D5.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000037",
        source: "FANTOM5",
        cell_line: "anaplastic large cell lymphoma cell line:Ki-JK",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/anaplastic%2520large%2520cell%2520lymphoma%2520cell%2520line%253aKi-JK.CNhs11881.10795-110I3.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000038",
        source: "FANTOM5",
        cell_line: "anaplastic squamous cell carcinoma cell line:RPMI 2650",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/anaplastic%2520squamous%2520cell%2520carcinoma%2520cell%2520line%253aRPMI%25202650.CNhs11889.10805-111A4.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000039",
        source: "FANTOM5",
        cell_line: "argyrophil small cell carcinoma cell line:TC-YIK",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/argyrophil%2520small%2520cell%2520carcinoma%2520cell%2520line%253aTC-YIK.CNhs11725.10589-108D4.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000040",
        source: "FANTOM5",
        cell_line: "astrocytoma cell line:TM-31",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/astrocytoma%2520cell%2520line%253aTM-31.CNhs10742.10425-106D2.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000041",
        source: "FANTOM5",
        cell_line: "b cell line:RPMI1788",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/b%2520cell%2520line%253aRPMI1788.CNhs10744.10427-106D4.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000042",
        source: "FANTOM5",
        cell_line: "B lymphoblastoid cell line: GM12878 ENCODE, biol_rep1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/B%2520lymphoblastoid%2520cell%2520line%253a%2520GM12878%2520ENCODE%252c%2520biol_rep1.CNhs12331.10821-111C2.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000043",
        source: "FANTOM5",
        cell_line: "B lymphoblastoid cell line: GM12878 ENCODE, biol_rep2",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/B%2520lymphoblastoid%2520cell%2520line%253a%2520GM12878%2520ENCODE%252c%2520biol_rep2.CNhs12332.10822-111C3.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000044",
        source: "FANTOM5",
        cell_line: "B lymphoblastoid cell line: GM12878 ENCODE, biol_rep3",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/B%2520lymphoblastoid%2520cell%2520line%253a%2520GM12878%2520ENCODE%252c%2520biol_rep3.CNhs12333.10823-111C4.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000045",
        source: "FANTOM5",
        cell_line: "basal cell carcinoma cell line:TE 354.T",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/basal%2520cell%2520carcinoma%2520cell%2520line%253aTE%2520354%252eT.CNhs11932.10702-109G9.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000046",
        source: "FANTOM5",
        cell_line: "bile duct carcinoma cell line:HuCCT1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/bile%2520duct%2520carcinoma%2520cell%2520line%253aHuCCT1.CNhs10750.10432-106D9.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000047",
        source: "FANTOM5",
        cell_line: "bile duct carcinoma cell line:TFK-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/bile%2520duct%2520carcinoma%2520cell%2520line%253aTFK-1.CNhs11265.10496-107C1.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000048",
        source: "FANTOM5",
        cell_line: "biphenotypic B myelomonocytic leukemia cell line:MV-4-11",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/biphenotypic%2520B%2520myelomonocytic%2520leukemia%2520cell%2520line%253aMV-4-11.CNhs11845.10718-109I7.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000049",
        source: "FANTOM5",
        cell_line: "bone marrow stromal cell line:StromaNKtert",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/bone%2520marrow%2520stromal%2520cell%2520line%253aStromaNKtert.CNhs11931.10686-109F2.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000050",
        source: "FANTOM5",
        cell_line: "Breast carcinoma cell line:MCF7",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/breast%2520carcinoma%2520cell%2520line%253aMCF7.CNhs11943.10482-107A5.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000051",
        source: "FANTOM5",
        cell_line: "Breast carcinoma cell line:MDA-MB-453",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/breast%2520carcinoma%2520cell%2520line%253aMDA-MB-453.CNhs10736.10419-106C5.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000052",
        source: "FANTOM5",
        cell_line: "bronchial squamous cell carcinoma cell line:KNS-62",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/bronchial%2520squamous%2520cell%2520carcinoma%2520cell%2520line%253aKNS-62.CNhs11862.10760-110E4.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000053",
        source: "FANTOM5",
        cell_line: "bronchioalveolar carcinoma cell line:NCI-H358",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/bronchioalveolar%2520carcinoma%2520cell%2520line%253aNCI-H358.CNhs11840.10709-109H7.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000054",
        source: "FANTOM5",
        cell_line: "bronchioalveolar carcinoma cell line:NCI-H650",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/bronchioalveolar%2520carcinoma%2520cell%2520line%253aNCI-H650.CNhs14138.10715-109I4.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000055",
        source: "FANTOM5",
        cell_line: "bronchogenic carcinoma cell line:ChaGo-K-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/bronchogenic%2520carcinoma%2520cell%2520line%253aChaGo-K-1.CNhs11841.10710-109H8.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000056",
        source: "FANTOM5",
        cell_line: "Burkitt's lymphoma cell line:DAUDI",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/Burkitt%2527s%2520lymphoma%2520cell%2520line%253aDAUDI.CNhs10739.10422-106C8.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000057",
        source: "FANTOM5",
        cell_line: "Burkitt's lymphoma cell line:RAJI",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/Burkitt%2527s%2520lymphoma%2520cell%2520line%253aRAJI.CNhs11268.10476-106I8.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000058",
        source: "FANTOM5",
        cell_line: "carcinoid cell line:NCI-H1770",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/carcinoid%2520cell%2520line%253aNCI-H1770.CNhs11834.10703-109H1.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000059",
        source: "FANTOM5",
        cell_line: "carcinoid cell line:NCI-H727",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/carcinoid%2520cell%2520line%253aNCI-H727.CNhs14244.10735-110B6.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000060",
        source: "FANTOM5",
        cell_line: "carcinoid cell line:SK-PN-DW",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/carcinoid%2520cell%2520line%253aSK-PN-DW.CNhs11846.10719-109I8.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000061",
        source: "FANTOM5",
        cell_line: "carcinosarcoma cell line:JHUCS-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/carcinosarcoma%2520cell%2520line%253aJHUCS-1.CNhs11747.10642-109A3.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000062",
        source: "FANTOM5",
        cell_line: "cervical cancer cell line:D98-AH2",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/cervical%2520cancer%2520cell%2520line%253aD98-AH2.CNhs11288.10552-107I3.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000063",
        source: "FANTOM5",
        cell_line: "cervical cancer cell line:ME-180",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/cervical%2520cancer%2520cell%2520line%253aME-180.CNhs11289.10553-107I4.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000064",
        source: "FANTOM5",
        cell_line: "cholangiocellular carcinoma cell line:HuH-28",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/cholangiocellular%2520carcinoma%2520cell%2520line%253aHuH-28.CNhs11283.10536-107G5.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000065",
        source: "FANTOM5",
        cell_line: "chondrosarcoma cell line:SW 1353",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chondrosarcoma%2520cell%2520line%253aSW%25201353.CNhs11833.10700-109G7.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000066",
        source: "FANTOM5",
        cell_line: "choriocarcinoma cell line:BeWo",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/choriocarcinoma%2520cell%2520line%253aBeWo.CNhs10740.10423-106C9.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000067",
        source: "FANTOM5",
        cell_line: "choriocarcinoma cell line:SCH",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/choriocarcinoma%2520cell%2520line%253aSCH.CNhs11875.10785-110H2.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000068",
        source: "FANTOM5",
        cell_line: "choriocarcinoma cell line:T3M-3",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/choriocarcinoma%2520cell%2520line%253aT3M-3.CNhs11820.10618-108G6.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000069",
        source: "FANTOM5",
        cell_line: "chronic lymphocytic leukemia (T-CLL) cell line:SKW-3",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chronic%2520lymphocytic%2520leukemia%2520%2528T-CLL%2529%2520cell%2520line%253aSKW-3.CNhs11714.10416-106C2.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000070",
        source: "FANTOM5",
        cell_line: "chronic myeloblastic leukemia (CML) cell line:KCL-22",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chronic%2520myeloblastic%2520leukemia%2520%2528CML%2529%2520cell%2520line%253aKCL-22.CNhs11886.10801-110I9.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000071",
        source: "FANTOM5",
        cell_line: "chronic myelogenous leukemia (CML) cell line:MEG-A2",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chronic%2520myelogenous%2520leukemia%2520%2528CML%2529%2520cell%2520line%253aMEG-A2.CNhs11865.10766-110F1.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000072",
        source: "FANTOM5",
        cell_line: "chronic myelogenous leukemia cell line:K562 ENCODE, biol_rep1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chronic%2520myelogenous%2520leukemia%2520cell%2520line%253aK562%2520ENCODE%252c%2520biol_rep1.CNhs12334.10824-111C5.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000073",
        source: "FANTOM5",
        cell_line: "chronic myelogenous leukemia cell line:K562 ENCODE, biol_rep2",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chronic%2520myelogenous%2520leukemia%2520cell%2520line%253aK562%2520ENCODE%252c%2520biol_rep2.CNhs12335.10825-111C6.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000074",
        source: "FANTOM5",
        cell_line: "chronic myelogenous leukemia cell line:K562 ENCODE, biol_rep3",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chronic%2520myelogenous%2520leukemia%2520cell%2520line%253aK562%2520ENCODE%252c%2520biol_rep3.CNhs12336.10826-111C7.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000075",
        source: "FANTOM5",
        cell_line: "chronic myelogenous leukemia cell line:K562",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chronic%2520myelogenous%2520leukemia%2520cell%2520line%253aK562.CNhs11250.10454-106G4.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000076",
        source: "FANTOM5",
        cell_line: "chronic myelogenous leukemia cell line:KU812",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/chronic%2520myelogenous%2520leukemia%2520cell%2520line%253aKU812.CNhs10727.10409-106B4.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000077",
        source: "FANTOM5",
        cell_line: "clear cell carcinoma cell line:JHOC-5",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/clear%2520cell%2520carcinoma%2520cell%2520line%253aJHOC-5.CNhs11745.10638-108I8.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000078",
        source: "FANTOM5",
        cell_line: "clear cell carcinoma cell line:TEN",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/clear%2520cell%2520carcinoma%2520cell%2520line%253aTEN.CNhs11930.10636-108I6.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000079",
        source: "FANTOM5",
        cell_line: "Colon carcinoma cell line:CACO-2",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/colon%2520carcinoma%2520cell%2520line%253aCACO-2.CNhs11280.10513-107D9.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000080",
        source: "FANTOM5",
        cell_line: "Colon carcinoma cell line:COLO-320",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/colon%2520carcinoma%2520cell%2520line%253aCOLO-320.CNhs10737.10420-106C6.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000081",
        source: "FANTOM5",
        cell_line: "cord blood derived cell line:COBL-a 24h infection(-C)",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/cord%2520blood%2520derived%2520cell%2520line%253aCOBL-a%252024h%2520infection%2528-C%2529.CNhs11049.10452-106G2.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000082",
        source: "FANTOM5",
        cell_line: "cord blood derived cell line:COBL-a 24h infection",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/cord%2520blood%2520derived%2520cell%2520line%253aCOBL-a%252024h%2520infection.CNhs11050.10453-106G3.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000083",
        source: "FANTOM5",
        cell_line: "cord blood derived cell line:COBL-a untreated",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/cord%2520blood%2520derived%2520cell%2520line%253aCOBL-a%2520untreated.CNhs11045.10449-106F8.hg19.ctss.bed.gz",
    },
    {
        type: "Histone modification sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000084",
        source: "FANTOM5",
        cell_line: "diffuse large B-cell lymphoma cell line:CTB-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/diffuse%2520large%2520B-cell%2520lymphoma%2520cell%2520line%253aCTB-1.CNhs11741.10631-108I1.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000085",
        source: "FANTOM5",
        cell_line: "ductal cell carcinoma cell line:KLM-1",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/ductal%2520cell%2520carcinoma%2520cell%2520line%253aKLM-1.CNhs11100.10438-106E6.hg19.ctss.bed.gz",
    },
    {
        type: "Expressed enhancer sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "POLR2",
        track: "NGFA000086",
        source: "FANTOM5",
        cell_line: "ductal cell carcinoma cell line:MIA Paca2",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/ductal%2520cell%2520carcinoma%2520cell%2520line%253aMIA%2520Paca2.CNhs11259.10488-107B2.hg19.ctss.bed.gz",
    },
    {
        type: "Transcription factor binding sites",
        diagnosis: "some fake diagnosis",
        cell: "some fake cell",
        description: "some fake description",
        antibody_target: "REST",
        track: "NGFA000087",
        source: "FANTOM5",
        cell_line: "embryonic Kidney cell line: HEK293/SLAM infection, 24hr",
        format: "bed bed6",
        url:
            "https://tf.lisanwanglab.org/GADB/Annotationtracks/FANTOM5/latest/basic/human.cell_line.hCAGE/bed6/hg19/embryonic%2520kidney%2520cell%2520line%253a%2520HEK293%252fSLAM%2520infection%252c%252024hr.CNhs11047.10451-106G1.hg19.ctss.bed.gz",
    },
];

export default tracks;
